TeknikServis.UI/Models/ServisTalebi.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel.DataAnnotations;
using TeknikServis.DTO;
using TeknikServis.UI.Models.dto;

namespace TeknikServis.UI.Models
{
    public class ServisTalebi
    {
        public int Id { get; set; }


        public int KullaniciId { get; set; }

        public int? UrunId { get; set; }

        public UrunDto? Urun { get; set; }
        [ValidateNever]
        public string UrunAdi { get; set; }

        public string Aciklama { get; set; }


        public string TalepDurumu { get; set; } = "Oluşturuldu";

        public DateTime TalepTarihi { get; set; } = DateTime.Now;

        public bool Durum { get; set; } = false; // false = Bekliyor, true = Çözüldü

        public virtual Kullanici? Kullanici { get; set; }

        public List<string> TalepResimleri { get; set; } = new List<string>();
    }
}

TeknikServis.UI/Controllers/RandevuController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http;
using System.Text;
using TeknikServis.DTO;

namespace TeknikServis.UI.Controllers
{
    public class RandevuController : Controller
    {
        private readonly HttpClient _httpClient;

        public RandevuController()
        {
            _httpClient = new HttpClient();
            _httpClient.BaseAddress = new Uri("https://localhost:44365/"); 
        }

        public async Task<IActionResult> Index()
        {
            string servisAdresi = "api/Randevu";

            if (HttpContext.Session.GetInt32("isAdmin") == 0)
            {
                servisAdresi += "/randevularByKullaniciId?id=" + HttpContext.Session.GetInt32("kullaniciId").Value;
            }

            var response = await _httpClient.GetAsync(servisAdresi);
            if (!response.IsSuccessStatusCode)
                return View(new List<RandevuDto>());

            var json = await response.Content.ReadAsStringAsync();
            var randevular = JsonConvert.DeserializeObject<List<RandevuDto>>(json);

            return View(randevular);
        }

        [HttpGet]
        public async Task<IActionResult> Create(int id, string musteriAdi, String urunAdi)
        {
            ViewBag.MusteriAdi =musteriAdi;
            ViewBag.UrunAdi = urunAdi;
            ViewBag.ServisTalebiId = id;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(RandevuDto dto)
        {

            string servisAdresi = $"api/Randevu/tarihlerandevu?tarih={Uri.EscapeDataString(dto.Tarihi.ToString("yyyy-MM-ddTHH:mm:ss"))}";

          
            var response1 = await _httpClient.GetAsync(servisAdresi);
            if (!response1.IsSuccessStatusCode)
                return View();

            var json = await response1.Content.ReadAsStringAsync();
            var randevu = JsonConvert.DeserializeObject<RandevuDto>(json);

            if(randevu != null)
            {
                ViewBag.MusteriAdi = randevu.ServisTalebi.Kullanici.AdSoyad;
                ViewBag.UrunAdi = randevu.ServisTalebi.Urun.Ad;
                ViewBag.ServisTalebiId = randevu.ServisTalebiId;
                ModelState.AddModelError("", "Bu tarihte zaten bir randevu var. Lütfen farklı bir tarih seçin.");
                return View(dto);
            }

            dto.RandevuDurumu = RandevuDurumu.PLANLANDI;
            var jsonData = JsonConvert.SerializeObject(dto);
            var content = new StringContent(jsonData, Encoding.UTF8, "application/json");

            var response = await _httpClient.PostAsync("api/Randevu", content);
            if (response.IsSuccessStatusCode)
                return RedirectToAction("Index");

            ModelState.AddModelError("", "Ekleme başarısız");
            return View(dto);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var response = await _httpClient.GetAsync($"api/Randevu/{id}");
            if (!response.IsSuccessStatusCode)
                return NotFound();

            var json = await response.Content.ReadAsStringAsync();
            var dto = JsonConvert.DeserializeObject<RandevuDto>(json);

            return View(dto);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(RandevuDto dto)
        {
            var jsonData = JsonConvert.SerializeObject(dto);
            var content = new StringContent(jsonData, Encoding.UTF8, "application/json");

            var response = await _httpClient.PutAsync($"api/Randevu/{dto.Id}", content);
            if (response.IsSuccessStatusCode)
                return RedirectToAction("Index");

            ModelState.AddModelError("", "Güncelleme başarısız");
            return View(dto);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var response = await _httpClient.DeleteAsync($"api/Randevu/{id}");
            return RedirectToAction("Index");
        }
    }
}

TeknikServis.UI/Controllers/ServisTalebiController.cs
using Microsoft.AspNetCore.Mvc;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using TeknikServis.UI.Models;
using Newtonsoft.Json;
using TeknikServis.UI.Models.dto;
using Microsoft.AspNetCore.Http;
using TeknikServis.DTO;
using Microsoft.AspNetCore.Mvc.Rendering;
using TeknikServis.UI.Helper;
using Microsoft.AspNetCore.Mvc.ModelBinding.Metadata;
using System.Reflection;

namespace TeknikServis.UI.Controllers
{
    public class ServisTalebiController : Controller
    {
        private readonly HttpClient _httpClient;
        private readonly HttpClient _httpClient2;

        public ServisTalebiController()
        {
            _httpClient = new HttpClient();
            _httpClient2 = new HttpClient();
        }

        [HttpGet]
        public async Task<IActionResult> TalepDetay(int id)
        {

            var response = await _httpClient.GetAsync("https://localhost:44365/api/ServisTalebi/"+id);

            ServisTalebiDto dto = null;

            if (response.IsSuccessStatusCode)
            {
                var json = await response.Content.ReadAsStringAsync();
                dto = JsonConvert.DeserializeObject<ServisTalebiDto>(json);
            }

            return View(dto);
        }

        [HttpGet]
        public async Task<JsonResult> GetUrunlerByKategori(int id)
        {
            var response = await _httpClient2.GetAsync("https://localhost:44365/api/Urun");
            var urunler = new List<UrunDto>();
            if (response.IsSuccessStatusCode)
            {
                var json = await response.Content.ReadAsStringAsync();
                urunler = JsonConvert.DeserializeObject<List<UrunDto>>(json);
            }

            return Json(urunler.Where(u => u.Kategorisi == (Kategori)id));
        }
        [HttpGet]
        public async Task<IActionResult> YeniTalep()
        {
            

           

            ViewBag.Kategoriler = EnumHelper.GetEnumDescriptions<Kategori>();

           

            var ad = HttpContext.Session.GetString("adSoyad");
            var email = HttpContext.Session.GetString("email");

            if (string.IsNullOrEmpty(ad) || string.IsNullOrEmpty(email))
            {
                return RedirectToAction("Login", "Kullanici");
            }

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> YeniTalep(ServisTalebiDto model, List<IFormFile> TalepResimleri)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Kategoriler = EnumHelper.GetEnumDescriptions<Kategori>();

                var ad = HttpContext.Session.GetString("adSoyad");
                var email = HttpContext.Session.GetString("email");
                return View();
            }
                

            if(TalepResimleri != null && TalepResimleri.Count > 0)
            {
                foreach(var resim in TalepResimleri)
                {
                    var upload = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/talep_resim");

                    var extension = Path.GetExtension(resim.FileName); //resim.png
                    var fileName = Guid.NewGuid().ToString() + extension; //dslfdslkfhsıy42r40389753.png
                    var filePath = Path.Combine(upload, fileName);

                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await resim.CopyToAsync(stream);
                    }

                    model.TalepResimleri.Add(fileName);

                }
            }


            model.TalepTarihi = DateTime.Now;

            model.KullaniciId = HttpContext.Session.GetInt32("kullaniciId").Value;

            var jsonData = JsonConvert.SerializeObject(model);
            var content = new StringContent(jsonData, Encoding.UTF8, "application/json");

            var response = await _httpClient.PostAsync("https://localhost:44365/api/ServisTalebi", content);

            if (response.IsSuccessStatusCode)
            {
                ViewBag.Mesaj = "Servis talebiniz başarıyla oluşturuldu!";
                return RedirectToAction("KendiTaleplerim");

            }

            var response2 = await _httpClient2.GetAsync("https://localhost:44365/api/Urun");
            var urunler = new List<UrunDto>();

            if (response2.IsSuccessStatusCode)
            {
                var json = await response2.Content.ReadAsStringAsync();
                urunler = JsonConvert.DeserializeObject<List<UrunDto>>(json);
            }

            ViewData["Urunler"] = urunler.Select(u => new SelectListItem
            {
                Value = u.Id.ToString(),
                Text = u.Ad
            });
            ViewBag.Mesaj = "Talep oluşturulurken hata oluştu!";
            ViewBag.Kategoriler = EnumHelper.GetEnumDescriptions<Kategori>();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Sil(int id)
        {
            var response = await _httpClient.DeleteAsync($"https://localhost:44365/api/ServisTalebi/{id}");

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("KendiTaleplerim");
            }
            else
            {
                TempData["SilmeHatasi"] = "Silme işlemi başarısız oldu!";
                return RedirectToAction("Index", "Home");
            }
        }
        [HttpGet]
        // ✅ Kullanıcının sadece kendi taleplerini gösteren kısım
        public async Task<IActionResult> KendiTaleplerim()
        {
            var kullaniciId = HttpContext.Session.GetInt32("kullaniciId");

            if (kullaniciId == null)
            {
                return RedirectToAction("Login", "Kullanici");
            }

            List<ServisTalebiDto> kullaniciTalepleri = new List<ServisTalebiDto>();

            var response = await _httpClient.GetAsync("https://localhost:44365/api/ServisTalebi");

            if (response.IsSuccessStatusCode)
            {
                var json = await response.Content.ReadAsStringAsync();
                var tumTalepler = JsonConvert.DeserializeObject<List<ServisTalebiDto>>(json);

                if (HttpContext.Session.GetInt32("isAdmin") == 0)
                {
                    kullaniciTalepleri = tumTalepler
                         .Where(t => t.KullaniciId == kullaniciId.Value)
                        .ToList();
                }
                else
                {
                    kullaniciTalepleri = tumTalepler;
                }

            }

            return View(kullaniciTalepleri.OrderByDescending(t=>t.TalepTarihi).ToList());
        }
    }
}

TeknikServis.UI/Views/ServisTalebi/KendiTaleplerim.cshtml
@model List<TeknikServis.DTO.ServisTalebiDto>


@{
    ViewData["Title"] = "Taleplerim";
}
<div class="d-flex justify-content-between align-items-center mb-3">
    <h2 class ="mb-4 text-center text-success">Servis Taleplerim</h2>
    <a class="btn btn-success btn-sm rounded shadow px-3" asp-controller="ServisTalebi" asp-action="YeniTalep">Servis Talebi Oluştur</a>
</div>

@if (Model != null && Model.Count > 0)
{
    <table class="table table-striped table-hover table-bordered table-responsive">
        <thead class="table-dark">
            <tr>
                <th>Ürün Adı</th>
                <th>Açıklama</th>
                <th>Talep Durumu</th>
                <th>Talep Tarihi</th>
                <th>Minimum Servis Ücreti</th>
                <th>Maximum Servis Ücreti</th>
                <th>Detay</th>
                <th>Randevu</th>
                <th>Sil</th>

            </tr>
        </thead>
        <tbody>
            @foreach (var talep in Model)
            {

                <tr>
                    <td>@talep.Urun.Ad</td>
                    <td>@talep.Aciklama</td>
                    <td>@talep.TalepDurumu</td>
                    <td>@talep.TalepTarihi?.ToString("dd.MM.yyyy HH:mm")</td>
                    <td>@talep.Urun.MinServisUcreti</td>
                    <td>@talep.Urun.MaxServisUcreti</td>
                    <td>
                        <a class="btn btn-primary" asp-action="TalepDetay" asp-route-id="@talep.Id">Detay</a>
                    </td>
                    <td>
                        @if (talep.Randevular.Select(r => r.RandevuDurumu != TeknikServis.DTO.RandevuDurumu.ONAYLANDI || r.RandevuDurumu != TeknikServis.DTO.RandevuDurumu.PLANLANDI).ToList().Count == 0)
                        {
                            <a class="btn btn-success" asp-action="Create" asp-controller="Randevu" asp-route-id="@talep.Id" asp-route-musteriAdi="@talep.Kullanici.AdSoyad" asp-route-urunAdi="@talep.Urun.Ad">Randevu</a>
                        }
                        else
                        {
                            <span class="text-info">Randevusu Var</span>
                        }
                    </td>

                    <td>
                        <form asp-controller="ServisTalebi" asp-action="Sil" method="post">
                            <input type="hidden" name="id" value="@talep.Id" />
                            <button type="submit" class="btn btn-danger btn-sm rounded shadow-sm px-3">Sil</button>
                        </form>
                    </td>

                </tr>
              
            }
        </tbody>
    </table>
}
else
{
    <div class="alert alert-warning">Henüz bir servis talebiniz bulunmamaktadır.</div>
}
<!-- SignalR client kütüphanesi -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/microsoft-signalr/7.0.5/signalr.min.js"></script>


<script>
    const connection = new signalR.HubConnectionBuilder()
        .withUrl("https://localhost:44365/hub/notification", {
            withCredentials: true
        })
        .build();

    connection.on("YeniTalep", function (message) {

       if(message === "YeniTalepEklendi"){
            location.reload();
       }
    });

    connection.start().catch(function (err) {
        console.error("SignalR bağlantı hatası:", err);
    });
</script>

<div id="talepListesi"></div>

TeknikServis.UI/Views/ServisTalebi/TalepDetay.cshtml
@model TeknikServis.DTO.ServisTalebiDto

@{
    ViewData["Title"] = "Details";
}



<div>
    <h4>ServisTalebi</h4>
    <hr />
    <dl class="row">

        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Urun.Ad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Urun.Ad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Aciklama)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Aciklama)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TalepDurumu)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TalepDurumu)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TalepTarihi)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TalepTarihi)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Urun.MinServisUcreti)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Urun.MinServisUcreti)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Urun.MaxServisUcreti)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Urun.MaxServisUcreti)
        </dd>

        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TalepResimleri)
        </dt>
        <dd class = "col-sm-10">
            @if (Model.TalepResimleri != null && Model.TalepResimleri.Count > 0)
            {
                foreach (string resim in Model.TalepResimleri)
                {
                    if (resim != null && resim != "") {
                        <div class="preview-container">
                            <img class="thumbnail" style="width:100px;height:80px" src="~/img/talep_resim/@resim" />

                        <div class="preview">
                            <img class="thumbnail" style="width:500px;height:450px" src="~/img/talep_resim/@resim" />

                        </div>
                    </div>
                    }
                    else
                    {
                        <p>Resim yüklenmemiş.</p>
                    }
                }
            }
            else
            {
                <p>Resim yüklenmemiş.</p>
            }
        </dd>
    </dl>
</div>
<div>

    <a asp-action="KendiTaleplerim">Geri Dön</a>
</div>

<style>
    .thumbnail {
        width: 150px;
        cursor: pointer;
    }

    .preview-container {
        position: relative;
        display: inline-block;
    }

    .preview {
        display: none;
        position: absolute;
        top: 0;
        left: 60px; /* küçük resmin sağında göster */
        border: 1px solid #ccc;
        background: white;
        z-index: 999;
        padding: 5px;
    }

        .preview img {
            width: 500px;
            height: auto;
        }

    .preview-container:hover .preview {
        display: block;

    }

</style>

TeknikServis.UI/Views/ServisTalebi/YeniTalep.cshtml
 @model TeknikServis.DTO.ServisTalebiDto

@{
    ViewData["Title"] = "Teknik Servis Talebi";
    var kullaniciId = Context.Session.GetInt32("kullaniciId") ?? 0;
}

<h2 class ="mb-4 text-center text-info">Teknik Servis Talebi Oluştur</h2>

<form id="talepForm" asp-action="YeniTalep" asp- enctype="multipart/form-data" method="post">

   
    <div class="form-group">

        <label for="urunAdi">Kategori Adı</label>
        <select name="KategoriId" id="KategoriId" class="form-control" onchange="getUrunlerByKategori()">
            <option>Kategori Seçiniz</option>
            @foreach(var kategori in (List<(int value, string Description)>)ViewBag.Kategoriler)
            {
                <option value="@kategori.value">@kategori.Description</option>
            }
        </select>
    </div>

    <div class="form-group">
        <label for="urunAdi">Ürün Adı</label>
        <select  name="UrunId" id="UrunId" class="form-control">
            <option>Önce Kategori Seçiniz</option>
        </select>
     
    </div>

    <div class="form-group">
        <label for="aciklama">Açıklama</label>
        <textarea asp-for="Aciklama" class="form-control" id="aciklama" required></textarea>
        <span asp-validation-for="Aciklama" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label for="aciklama">Talep Resimleri</label>
        <input type="file" id="TalepResimleri" name="TalepResimleri" multiple>
    </div>

    <input type="hidden" id="kullaniciIdInput" value="@kullaniciId" />

    <input type="submit" value="Gönder" class="btn btn-primary btn-sm rounded shadow-sm px-3 mt-3" />
    @* <button type="button" onclick="talepGonder()" class="btn btn-primary btn-sm rounded shadow-sm px-3">Gönder</button>   *@
</form>

<script>
    function getUrunlerByKategori() {

        let categoryId = document.getElementById("KategoriId").value;

        fetch(`/ServisTalebi/GetUrunlerByKategori?id=${categoryId}`)
            .then(response => {
                if (!response.ok) {
                    throw new Error("Sunucu hatası!");
                }
                return response.json();
            })
            .then(data => {
                console.log("Gelen Ürünler:", data);

                // Örnek: Verileri HTML'e eklemek
                const urunListesi = document.getElementById("UrunId");
            

               // Önceki seçenekleri temizle
            urunListesi.innerHTML = "<option value=''>Ürün Seçiniz</option>";

            // Gelen ürünleri ekle
            data.forEach(urun => {
                const option = document.createElement("option");
                option.value = urun.id;
                option.textContent = urun.ad + " (Min. Servis Ücreti :"+urun.minServisUcreti+" - Max. Servis Ücreti :"+urun.maxServisUcreti+")";
                urunListesi.appendChild(option);
            });
            })
            .catch(error => {
                console.error("Hata oluştu:", error);
            });
    }


    function talepGonder() {
        const kullaniciId = parseInt(document.getElementById("kullaniciIdInput").value);

        if (!kullaniciId || isNaN(kullaniciId)) {
            alert("Kullanıcı bilgisi alınamadı.");
            return;
        }

        const resimler =  document.getElementById("TalepResimleri").value;
        debugger;
        const talep = {
           urunAdi: "",
           urunId: document.getElementById("UrunId").value,
            aciklama: document.getElementById("aciklama").value,
            kullaniciId: kullaniciId,
            talepDurumu: "Oluşturuldu",
            talepResimleri : "",
            talepTarihi: null
        };

        fetch("https://localhost:44365/api/ServisTalebi", {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "kullaniciId": kullaniciId  // Session'dan gelen ID'yi header'a ekliyoruz
            },
            body: JSON.stringify(talep)
        })
        .then(response => {
            if (response.ok) {
                alert("Talep başarıyla gönderildi!");
                location.href = "KendiTaleplerim";
            } else {
                response.text().then(text => alert("Sunucu hatası: " + text));
            }
        })
        .catch(error => {
            console.error("Fetch hatası:", error);
            alert("Beklenmedik bir hata oluştu.");
        });
    }
</script>